// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flpimjforqtcqzwmrmcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZscGltamZvcnF0Y3F6d21ybWNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MzA2ODAsImV4cCI6MjA2MDAwNjY4MH0.E_1NGhn1N_8JLD7oM2UGoNviyQuAyMiVc6eO5V7yKEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);